- name: Install necessary dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - apt-transport-https
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Create project directory
  ansible.builtin.file:
    path: /root/warpgate/
    state: directory

- name: Create data folder
  ansible.builtin.file:
    path: /root/warpgate/data
    state: directory

- name: Delete warpgate binary if it exists
  ansible.builtin.file:
    path: /root/warpgate/warpgate
    state: absent

- name: Download warpgate binary
  ansible.builtin.get_url:
    url: https://github.com/warp-tech/warpgate/releases/download/v0.11.0/warpgate-v0.11.0-x86_64-linux
    dest: /root/warpgate/warpgate
    mode: "744"
    owner: root

- name: Delete Old warpgate config file if it already exists
  ansible.builtin.file:
    path: /etc/warpgate.yaml
    state: absent

- name: Create warpgate config file
  ansible.builtin.command:
    chdir: /root/warpgate/
    argv:
      - /root/warpgate/warpgate
      - unattended-setup
      - --data-path=/data
      - --http-port=8888
      - --ssh-port=2222
      - --mysql-port=33306
      - --record-sessions
      - --admin-password={{ warpgate_admin_pass }}

- name: Add Warpgate service file to server
  ansible.builtin.copy:
    src: files/warpgate.service
    dest: /etc/systemd/system/warpgate.service
    mode: "744"
    owner: root

- name: Enable and run  Warpgate service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: warpgate
    state: restarted
