- name: Install necessary dependencies
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - apt-transport-https
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Add Docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create project directory
  ansible.builtin.file:
    path: /root/warpgate/
    state: directory

- name: Create data folder
  ansible.builtin.file:
    path: /root/warpgate/data
    state: directory

- name: Add docker compose file to server
  ansible.builtin.copy:
    src: files/compose.yml
    dest: /root/warpgate/

- name: Delete Old warpgate config file if it already exists
  ansible.builtin.file:
    path: /root/warpgate/data/warpgate.yaml
    state: absent

- name: Create warpgate config file
  community.docker.docker_compose_v2_run:
    project_src: /root/warpgate/
    service: warpgate
    argv:
      - unattended-setup
      - --data-path=/data
      - --http-port=8888
      - --ssh-port=2222
      - --mysql-port=33306
      - --record-sessions
      - --admin-password="{{ warpgate_admin_pass }}"

- name: Bring the docker compose down if is running
  community.docker.docker_compose_v2:
    project_src: /root/warpgate/
    state: absent

- name: Bring the docker compose up
  community.docker.docker_compose_v2:
    project_src: /root/warpgate/
  register: warpgate_compose_output
