# provided by Warpgate 
# https://github.com/warp-tech/warpgate/wiki/Getting-started-on-Docker
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true